{{- $ns := include "workshop.namespace" . }}
{{- range .Values.connections }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $ns }}
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
    opendatahub.io/connection-type-protocol: s3
    opendatahub.io/connection-type-ref: s3
    openshift.io/display-name: {{ .name }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ $.Values.rootUser | quote }}
  AWS_SECRET_ACCESS_KEY: {{ $.Values.rootPassword | quote }}
  AWS_DEFAULT_REGION: {{ $.Values.region | quote }}
  AWS_S3_ENDPOINT: http://minio-service.{{ $ns }}.svc.cluster.local:9000
  AWS_S3_BUCKET: {{ .bucket | quote }}
{{- end }}
