---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: {{ include "workshop.namespace" . }}
stringData:
  minio_root_user: {{ .Values.rootUser | quote }}
  minio_root_password: {{ .Values.rootPassword | quote }}
