{{- if .Values.gateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
  - name: https
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: {{ .Values.gateway.certificateSecret }}
        kind: Secret
    allowedRoutes:
      namespaces:
        from: All
{{- end }}
