---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "workshop.namespace" . }}
  labels:
    opendatahub.io/dashboard: {{ .Values.dashboardLabel | quote }}
    opendatahub.io/generated-namespace: "true"
    app.kubernetes.io/component: workshop-namespace
    evalhub.trustyai.opendatahub.io/tenant: "true"
  annotations:
    openshift.io/display-name: "Workspace {{ .Values.username }}"
    openshift.io/description: "Fed Aura Capital workshop namespace for {{ .Values.username }}"
