{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.route.name }}
  namespace: {{ include "workshop.namespace" . }}
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: openshell
  port:
    targetPort: 8080
{{- end }}
