---
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: {{ include "workshop.namespace" . }}
spec:
  apiServer:
    caBundleFileMountPath: ''
    caBundleFileName: ''
    deploy: true
    artifactSignedURLExpirySeconds: 60
    enableSamplePipeline: false
    managedPipelines: {}
    enableOauth: true
    cacheEnabled: true
    pipelineStore: kubernetes
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: {{ .Values.database.pvcSize }}
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      basePath: ''
      bucket: {{ .Values.objectStorage.bucket }}
      host: minio-service.{{ include "workshop.namespace" . }}.svc.cluster.local:9000
      port: ''
      region: {{ .Values.objectStorage.region }}
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: {{ .Values.objectStorage.secretName }}
      scheme: http
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: true
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
