{{- if .Values.dataScienceCluster.create }}
apiVersion: datasciencecluster.opendatahub.io/{{ .Values.dataScienceCluster.version }}
kind: DataScienceCluster
metadata:
  name: default-dsc
  annotations:
    # The CRD only exists once the operator has installed, so skip the dry run.
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
{{- if .Values.dataScienceCluster.components }}
spec:
  components:
    {{- toYaml .Values.dataScienceCluster.components | nindent 4 }}
{{- else }}
spec: {}
{{- end }}
{{- end }}
