{{- with .Values.dataScienceClusterInitialization }}
apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  name: default-dsci
  annotations:
    # The CRD only exists once the operator has installed, so skip the dry run.
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
