{{- if .Values.catalog.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gen-ai-aa-mcp-servers
  namespace: {{ .Values.dashboardNamespace }}
data:
  {{- if .Values.riskServer.enabled }}
  Risk-MCP-Server: |
    {
      "url": "http://mcp-risk-server.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.riskServer.port }}/mcp",
      "transport": "streamable-http",
      "description": "An MCP server for mortgage risk assessment and analysis."
    }
  {{- end }}
  {{- if .Values.weatherServer.enabled }}
  Weather-MCP-Server: |
    {
      "url": "http://mcp-weather.{{ .Values.namespace }}.svc.cluster.local/sse",
      "transport": "sse",
      "description": "An MCP server for getting real-time weather data."
    }
  {{- end }}
{{- end }}
