---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSAuthPolicy
metadata:
  name: {{ .Values.model.name }}-access
  namespace: {{ .Values.namespaces.tenant }}
spec:
  modelRefs:
    - name: {{ .Values.model.name }}
      namespace: {{ .Values.namespaces.externalModels }}
  subjects:
    groups:
      - name: system:authenticated
{{- range .Values.subscriptions }}
---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSSubscription
metadata:
  name: {{ $.Values.model.name }}-{{ .name }}
  namespace: {{ $.Values.namespaces.tenant }}
  {{- with .displayName }}
  annotations:
    openshift.io/display-name: {{ . | quote }}
  {{- end }}
spec:
  modelRefs:
    - name: {{ $.Values.model.name }}
      namespace: {{ $.Values.namespaces.externalModels }}
      tokenRateLimits:
        - limit: {{ .tokenLimit }}
          window: {{ .window }}
  owner:
    groups:
      - name: system:authenticated
  priority: {{ .priority }}
{{- end }}
