---
apiVersion: maas.opendatahub.io/v1alpha1
kind: Config
metadata:
  name: default
spec:
  limitadorScrapeInterval: 30s
  usageLogging: false
---
apiVersion: maas.opendatahub.io/v1alpha1
kind: AITenant
metadata:
  name: {{ .Values.namespaces.tenant }}
  namespace: {{ .Values.namespaces.aiTenants }}
spec:
  gateway:
    name: {{ .Values.gateway.name }}
---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaasTenantConfig
metadata:
  name: default-tenant
  namespace: {{ .Values.namespaces.tenant }}
  labels:
    ai-gateway.opendatahub.io/tenant: {{ .Values.namespaces.tenant }}
    maas.opendatahub.io/tenant-name: {{ .Values.namespaces.tenant }}
    maas.opendatahub.io/tenant-namespace: {{ .Values.namespaces.tenant }}
spec: {}
