{{- if .Values.llmd.enabled }}
---
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceServiceConfig
metadata:
  annotations:
    description: Standard single-node CPU deployment with intelligent scheduling. Suitable for testing llm-d with CPUs.
    openshift.io/description: ''
    openshift.io/display-name: cpu-single-node
  name: cpu-single-node
  namespace: {{ .Values.dashboardNamespace }}
  finalizers:
    - serving.kserve.io/llmisvcconfig-finalizer
  labels:
    opendatahub.io/config-type: workload-single-node
    opendatahub.io/dashboard: 'true'
spec:
  model:
    uri: ''
  template:
    containers:
      - image: '{{ .Values.llmd.image }}'
        name: main
        resources:
          limits:
            cpu: '4'
            memory: 32Gi
          requests:
            cpu: '2'
            memory: 16Gi
{{- end }}
